### ISSUE TITLE
`removeAllListeners` is not a function?

### ISSUE THREAD

**Issue by bradisbell** [medikoo/observable-array#2]
I can't seem to figure out how to remove an event handler for the `change` event.  `removeAllListeners` doesn't seem to be defined.

**Comment by medikoo** [comment]
ObservableArray implements [event-emitter](https://github.com/medikoo/event-emitter#event-emitter), so:

To remove single handler you do:

``` javascript
array.off('change', handler);
```

If you want to clear all handlers, there's no directly defined method for that, but there's an util:

``` javascript
var allOff = require('event-emitter/all-off');

allOff(array, 'change')
```
