### ISSUE TITLE
Trying to use the set() and setItem() methods

### ISSUE THREAD

**Issue by emmanuel128** [medikoo/observable-array#3]
I'm trying to change a value of a ObservableArray called airlines. The structure of the array is
```
[
   {
     FullName: "",
     Id: ""
   },
   {
     FullName: "",
     Id: ""
   }
   ...
   ..
   .
]
```

I saw on the internet to make it this way but it doesn't work

```
                var index = id + ".FullName";
                // console.log("index: " + index);   => Ex. "3.FullName"
                viewModel.airlines.set(index, name);
```

**Comment by medikoo** [comment]
@emmanuel128 What dictates shape of an array is strictly values stored at _numeric_ indexes (so properties named `'0'`, `'1'`, `'3'` etc.) Any other named properties (as e.g. `foo`, or `3.FullName`) same as in case of normal array won't have any effect on it's `length` or any other array specific characteristics that is observed.

See how it works on regular array:
```javascript
// Regular array:
var arr = [1, 2];
arr.length; // 2
arr[2] = 'foo';
arr.length; // 3 (setting numeric index above changed shape of an array)
arr[3 + 'elo'] = 'bar';
arr.length; // 3 (above had no effect on array)
```

With ObservableArray you get similiar behavior, however when you pass not numeric index  (one for which `isNaN(value) === true`) to `set` method, it gets coerced to `0` (I think it would be better if it would crash, so I've opened issue to address that: #4) so effect is as below:

```javascript
var oArr = new ObservableArray(1, 2);
oArr.length; // 2
oArr.set(2, 'foo');
oArr.length; // 3 (setting numeric index above changed shape of an array)
oArr.set(3 + 'elo', 'bar'); // Not numeric index, so call got coerced to arr.set(0, 'bar');
oArr.length; // 3 (above didn't changed length but replaced value at `0` index
```

Anyway, you're free to set normal properties on ObservableArray as you do to Array's, but do not use `set` in this case, and also do not expect any _observability_ mechanisms to be triggered by that, e.g.:

```
oArr[3 + 'elo'] = 'bar'; // Fine, totally has no effect on array shape
oArr.length; // 3
```
