### ISSUE TITLE
Question about optionally enforcing the type of each item? 

### ISSUE THREAD

**Issue by jfgrissom** [medikoo/observable-array#5]
Hi Mariusz,

Thanks for making this module. It fits a need I have perfectly.

I'm using this with node.js and typescript and I would like to enforce the data types being stored in this ObservableArray.

Does it make sense to add an optional feature to enforce the type of objects this observable is willing to store?

```
import { CustomObject }  from './../interfaces/custom-object';
import * as ObservableArray from 'observable-array';

let oArr = ObservableArray();
oArr.constrainItemsToType(CustomObject);
```

If you think this is worth while to add I'll fork this and create a PR for you to review.

Thanks,
Jay

**Comment by medikoo** [comment]
@jfgrissom great thanks for interest. However I'd like to keep this module agnostic to types (as native array is).

I can imagine some extension to `ObservableArray` that provides such feature, still I believe it's best if that's developed as an external module (e.g. `observable-array-typed`).
